/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemshs;

import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Student Log-in
 */
public class MAINTEACHER extends javax.swing.JFrame {
Connection con=null;
    PreparedStatement pst =null;
     ResultSet rs =null;
    /**
     * Creates new form MAINTEACHER
     */
    public MAINTEACHER() {
        initComponents();
         con=SYSTEMSHS.connect();
         loadTable();
        off();
    }
public void off(){
   
    lrn.setEnabled(false);
    fn.setEnabled(false);
    ln.setEnabled(false);
    mi.setEnabled(false);
    remarks.setEnabled(false);
    combo.setEnabled(false);
    male.setEnabled(false);
    female.setEnabled(false);
    in.setEnabled(false);
    out.setEnabled(false);
    date.setEnabled(false);
   id.setEnabled(false);
    exit.setEnabled(false);
    g.setEnabled(true);
    
}
    
    

      public void loadTable(){
        try {
            String sql = "select * from MAIN";
            pst = con.prepareStatement(sql);
            rs= pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
                
        }catch (Exception e)
        {
            
        }
      }
        String gender="";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lrn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        mi = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        g = new javax.swing.JTextField();
        remarks = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        out = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        in = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        del1 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Student ID :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 10, 100, 30);
        jPanel2.add(id);
        id.setBounds(10, 50, 160, 30);

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LRN :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 80, 100, 30);
        jPanel2.add(lrn);
        lrn.setBounds(10, 120, 160, 30);

        jLabel15.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("First Name :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(30, 160, 120, 30);
        jPanel2.add(fn);
        fn.setBounds(10, 200, 160, 30);

        jLabel17.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Last Name :");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(40, 250, 100, 30);
        jPanel2.add(ln);
        ln.setBounds(10, 290, 160, 30);

        jLabel16.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Middle Name :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 330, 110, 30);
        jPanel2.add(mi);
        mi.setBounds(10, 370, 160, 30);

        jLabel24.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Grade :");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(30, 410, 110, 30);
        jPanel2.add(g);
        g.setBounds(10, 450, 160, 30);
        jPanel2.add(remarks);
        remarks.setBounds(190, 450, 160, 30);

        jLabel23.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Remarks");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(210, 410, 110, 30);
        jPanel2.add(out);
        out.setBounds(190, 370, 160, 30);

        jLabel18.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Time Out :");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(220, 330, 100, 30);
        jPanel2.add(in);
        in.setBounds(190, 290, 160, 30);

        jLabel19.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Time In :");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(220, 250, 100, 30);

        male.setBackground(new java.awt.Color(153, 153, 153));
        male.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        male.setText("Male");
        jPanel2.add(male);
        male.setBounds(200, 210, 60, 25);

        female.setBackground(new java.awt.Color(153, 153, 153));
        female.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        female.setText("Female");
        jPanel2.add(female);
        female.setBounds(270, 210, 70, 25);

        jLabel20.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Gender :");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(210, 170, 100, 30);
        jPanel2.add(date);
        date.setBounds(190, 130, 160, 30);

        jLabel22.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Date :");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(220, 90, 100, 30);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Charles Babbage", "Steve Jobs" }));
        jPanel2.add(combo);
        combo.setBounds(190, 50, 160, 30);

        jLabel25.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Section :");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(210, 10, 100, 30);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamge/asss.jpg"))); // NOI18N
        jLabel21.setText("Search :");
        jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel21.setOpaque(true);
        jPanel2.add(jLabel21);
        jLabel21.setBounds(460, 30, 100, 30);
        jPanel2.add(search);
        search.setBounds(560, 30, 310, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(370, 90, 500, 330);

        del1.setBackground(new java.awt.Color(255, 255, 255));
        del1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        del1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamge/asd.png"))); // NOI18N
        del1.setText("DELETE");
        del1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del1ActionPerformed(evt);
            }
        });
        jPanel2.add(del1);
        del1.setBounds(380, 430, 150, 40);

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamge/d.png"))); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit);
        edit.setBounds(550, 430, 150, 40);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamge/as.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit);
        exit.setBounds(720, 430, 150, 40);

        jTabbedPane1.addTab("Computer Monitor Log Record", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        jPanel4.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(410, 30, 452, 402);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 890, 470);

        jTabbedPane1.addTab("Account Monitor in Student", jPanel3);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 890, 520);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 80, 890, 520);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Monitor Log Record");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 90);

        setSize(new java.awt.Dimension(907, 641));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
 try{
        DefaultTableModel al = (DefaultTableModel) table.getModel();
        int selectedRowIndex = table.getSelectedRow();
        id.setText(al.getValueAt(selectedRowIndex, 0).toString());
        lrn.setText(al.getValueAt(selectedRowIndex, 1).toString());
        fn.setText(al.getValueAt(selectedRowIndex, 2).toString());
        ln.setText(al.getValueAt(selectedRowIndex, 3).toString());
        mi.setText(al.getValueAt(selectedRowIndex, 4).toString());
        g.setText(al.getValueAt(selectedRowIndex, 5).toString());
        combo.setSelectedItem(al.getValueAt(selectedRowIndex, 6).toString());
         Date date1 = new SimpleDateFormat("MMM d, yyyy").parse((String)table.getValueAt(selectedRowIndex, 7));
         date.setDate(date1);
         String gender= al.getValueAt(selectedRowIndex, 8).toString();
        if(gender.equals("Male")){
            male.setSelected(true);
           
        }
         else{
            female.setSelected(true);
             }    
        in.setText(al.getValueAt(selectedRowIndex, 9).toString());
        out.setText(al.getValueAt(selectedRowIndex, 10).toString());
        remarks.setText(al.getValueAt(selectedRowIndex, 11).toString());
          
 }
 catch(Exception e)
 {
     
 }
    }//GEN-LAST:event_tableMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    try {
            String val1 = id.getText();
            String val2 = lrn.getText();
            String val3 = fn.getText();
            String val4 = ln.getText();
            String val5 = mi.getText();
            String val6 = g.getText();
            String val7 = combo.getSelectedItem().toString();
            
           
            String val9= gender;
            String val10 = in.getText();
            String val11 = out.getText();
            String val12 = remarks.getText();
            

            String sql = "update MAIN set LRN='" + val2 + "',FirstName='" + val3 + "',LastName='" + val4 +"',MiddleName='" + val5 + "',Grade='" + val6 +"',Section='" + val7 + "',Gender='" + val9 +"',TimeIn='" + val10 +"',TimeOut='" + val11 +"',Remarks='" + val12 +"'where StudentID='" + val1 + "'";

            pst = con.prepareStatement(sql);
            pst.execute();
            loadTable();

            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_editActionPerformed

    private void del1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_del1ActionPerformed

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed
  lrn.setEnabled(true);
    fn.setEnabled(true);
    ln.setEnabled(true);
    mi.setEnabled(true);
    remarks.setEnabled(true);
    combo.setEnabled(true);
    male.setEnabled(true);
    female.setEnabled(true);
    in.setEnabled(true);
    out.setEnabled(true);
    date.setEnabled(true);
   id.setEnabled(true);
    exit.setEnabled(true);
    g.setEnabled(true);        
    }//GEN-LAST:event_tableMousePressed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAINTEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAINTEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAINTEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAINTEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINTEACHER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton del1;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField g;
    private javax.swing.JTextField id;
    private javax.swing.JTextField in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField lrn;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mi;
    private javax.swing.JTextField out;
    private javax.swing.JTextField remarks;
    private javax.swing.JTextField search;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
